### admin register (requires ADMIN_REGISTRATION_KEY from .env)
POST http://localhost:5000/auth/admin
Content-Type: application/json

{
	"firstName":"admin",
	"lastName":"",
	"email":"admin@gmail.com",
	"password":"admin123",
	"profileImageUrl":"",
	"adminKey":"admin123"
	
}

### admin login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
	"email":"admin@gmail.com",
	"password":"admin123"
}

### read all USERS & AUTHORS data (read only emails of users and authors)
GET http://localhost:5000/admin-api/users

### BLock or active user or author
PATCH http://localhost:5000/admin-api/user
Content-Type: application/json

{
 "email":"user1@gmail.com",
 "isUserActive": true
}